### ISSUE TITLE
why is the result of RCNN is about 25%?

### ISSUE THREAD

**Issue by WindHunter-Yang** [AnubhavGupta3377/Text-Classification-Models#1]
I don't know why , I just add the code in config.py
max_sen_len = None

can you give me some ideas,thanks

**Comment by WindHunter-Yang** [comment]
My loss value is about 
Iter: 1
	Average training loss: -0.26572
	Val Accuracy: 0.2454
Iter: 101
	Average training loss: -0.25329
	Val Accuracy: 0.2453
Iter: 201
	Average training loss: -0.25105
	Val Accuracy: 0.2445
Iter: 301
	Average training loss: -0.25299
	Val Accuracy: 0.2436
Iter: 401
	Average training loss: -0.25069
	Val Accuracy: 0.2449
Iter: 501
	Average training loss: -0.25378
	Val Accuracy: 0.2444
Iter: 601
	Average training loss: -0.25145
	Val Accuracy: 0.2437
Iter: 701
	Average training loss: -0.24823
	Val Accuracy: 0.2447
Final Training Accuracy: 0.2508
Final Validation Accuracy: 0.2455
Final Test Accuracy: 0.2468

**Comment by AnubhavGupta3377** [comment]
Are you using some other dataset?
Accuracy may be different for different datasets.

Also, did you change the optimization objective?
Different objectives requires different learning rates.

**Comment by WindHunter-Yang** [comment]
> Are you using some other dataset?
> Accuracy may be different for different datasets.
> 
> Also, did you change the optimization objective?
> Different objectives requires different learning rates.

I use the AG news，when I run the code ,it will have a problem:ValueError: optimizing a parameter that doesn't require gradients
I change the code : optimizer = optim.SGD(filter(lambda p: p.requires_grad,model.parameters()),lr=config.lr)
How to solve this problem？

**Comment by AnubhavGupta3377** [comment]
For which parameter are you getting the error **ValueError: optimizing a parameter that doesn't require gradients**?

Have you changed the code anywhere else?

You can see the result of my run here: https://www.kaggle.com/anubhav3377/model-rcnn

I am running it with same parameters. Please check if you are missing something.

**Comment by WindHunter-Yang** [comment]
sorry,I can't look through this website, it will hint "We can't find that page"
my config.py ：
class Config(object):
    embed_size = 300
    hidden_layers = 1
    hidden_size = 64
    output_size = 4
    max_epochs = 3
    hidden_size_linear = 64
    lr = 0.5
    batch_size = 128
    seq_len = None # Sequence length for RNN
    dropout_keep = 0.8
    max_sen_len = 50
I add the max_sen_len
I also change the code:
train_examples = [data.Example.fromlist(str(i), datafields) for i in train_df.values.tolist()]
test_examples = [data.Example.fromlist(str(i), datafields) for i in test_df.values.tolist()]
That's all

**Comment by AnubhavGupta3377** [comment]
Now you should be able to access the Kaggle link.

One more question: why did you need to make the changes?
The code should work as is, after copying the Glove embeddings file and dataset into data/ directory.

**Comment by WindHunter-Yang** [comment]
Yes,I accept it, thank you.
I use the torch version is 0.4
This question,if i don't add str(),it will hint
    train_examples = [data.Example.fromlist(i, datafields) for i in train_df.values.tolist()]
  File "C:\Users\91596\Anaconda3\envs\python35\lib\site-packages\torchtext\data\example.py", line 52, in fromlist
    setattr(ex, name, field.preprocess(val))
  File "C:\Users\91596\Anaconda3\envs\python35\lib\site-packages\torchtext\data\field.py", line 181, in preprocess
    x = Pipeline(six.text_type.lower)(x)
  File "C:\Users\91596\Anaconda3\envs\python35\lib\site-packages\torchtext\data\pipeline.py", line 37, in __call__
    x = pipe.call(x, *args)
  File "C:\Users\91596\Anaconda3\envs\python35\lib\site-packages\torchtext\data\pipeline.py", line 53, in call
    return self.convert_token(x, *args)
TypeError: descriptor 'lower' requires a 'str' object but received a 'int'

**Comment by AnubhavGupta3377** [comment]
Are you able to run it now?

Was the Torch version only problem? I didn't suspect that it will prevent the model from training anything at all.

**Comment by WindHunter-Yang** [comment]
Thank you for your letter,I copy your code from the link,it also have two promblem by using torch 0.4:
the first is :
Traceback (most recent call last):
  File "E:/torch_workspace/Text-Classification-Models-Pytorch-master/Text-Classification-Models-Pytorch-master/Model_RCNN/train.py", line 21, in <module>
    dataset.load_data(w2v_file, train_file, test_file)
  File "E:\torch_workspace\Text-Classification-Models-Pytorch-master\Text-Classification-Models-Pytorch-master\Model_RCNN\utils.py", line 69, in load_data
    test_examples = [data.Example.fromlist(i, datafields) for i in test_df.values.tolist()]
  File "E:\torch_workspace\Text-Classification-Models-Pytorch-master\Text-Classification-Models-Pytorch-master\Model_RCNN\utils.py", line 69, in <listcomp>
    test_examples = [data.Example.fromlist(i, datafields) for i in test_df.values.tolist()]
  File "C:\Users\91596\Anaconda3\envs\python35\lib\site-packages\torchtext\data\example.py", line 52, in fromlist
    setattr(ex, name, field.preprocess(val))
  File "C:\Users\91596\Anaconda3\envs\python35\lib\site-packages\torchtext\data\field.py", line 181, in preprocess
    x = Pipeline(six.text_type.lower)(x)
  File "C:\Users\91596\Anaconda3\envs\python35\lib\site-packages\torchtext\data\pipeline.py", line 37, in __call__
    x = pipe.call(x, *args)
  File "C:\Users\91596\Anaconda3\envs\python35\lib\site-packages\torchtext\data\pipeline.py", line 53, in call
    return self.convert_token(x, *args)
TypeError: descriptor 'lower' requires a 'str' object but received a 'int'

I change the code:
# Load data from pd.DataFrame into torchtext.data.Dataset
train_df = self.get_pandas_df(train_file)
train_examples = [data.Example.fromlist(str(i), datafields) for i in train_df.values.tolist()]
train_data = data.Dataset(train_examples, datafields)

test_df = self.get_pandas_df(test_file)
test_examples = [data.Example.fromlist(str(i), datafields) for i in test_df.values.tolist()]
test_data = data.Dataset(test_examples, datafields)

The second is:
Loaded 96000 training examples Loaded 7600 test examples Loaded 24000 validation examples C:\Users\91596\Anaconda3\envs\python35\lib\site-packages\torch\nn\modules\rnn.py:38: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.8 and num_layers=1   "num_layers={}".format(dropout, num_layers)) Traceback (most recent call last):   File "E:/torch_workspace/Text-Classification-Models-Pytorch-master/Text-Classification-Models-Pytorch-master/Model_RCNN/train.py", line 29, in <module>     optimizer = optim.SGD(model.parameters(), lr=config.lr)   File "C:\Users\91596\Anaconda3\envs\python35\lib\site-packages\torch\optim\sgd.py", line 64, in __init__     super(SGD, self).__init__(params, defaults)   File "C:\Users\91596\Anaconda3\envs\python35\lib\site-packages\torch\optim\optimizer.py", line 43, in __init__     self.add_param_group(param_group)   File "C:\Users\91596\Anaconda3\envs\python35\lib\site-packages\torch\optim\optimizer.py", line 193, in add_param_group     raise ValueError("optimizing a parameter that doesn't require gradients") ValueError: optimizing a parameter that doesn't require gradients

I change the code:
optimizer = optim.SGD(filter(lambda p: p.requires_grad, model.parameters()), lr=config.lr)

The result:(The result still is not correct)
Loaded 96000 training examples Loaded 7600 test examples Loaded 24000 validation examples C:\Users\91596\Anaconda3\envs\python35\lib\site-packages\torch\nn\modules\rnn.py:38: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.8 and num_layers=1   "num_layers={}".format(dropout, num_layers)) Epoch: 0 E:\torch_workspace\Text-Classification-Models-Pytorch-master\Text-Classification-Models-Pytorch-master\Model_RCNN\model.py:68: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.   return self.softmax(final_out)
 Iter: 1 	Average training loss: -0.24916 	Val Accuracy: 0.2522 Iter: 101 	Average training loss: -0.24935 	Val Accuracy: 0.2540 Iter: 201 	Average training loss: -0.24733 	Val Accuracy: 0.2537 Iter: 301 	Average training loss: -0.24710 	Val Accuracy: 0.2515 Iter: 401 	Average training loss: -0.25116 	Val Accuracy: 0.2532 Iter: 501 	Average training loss: -0.24834 	Val Accuracy: 0.2525 Iter: 601 	Average training loss: -0.24432 	Val Accuracy: 0.2534 Iter: 701 	Average training loss: -0.24576 	Val Accuracy: 0.2560 
Epoch: 1 Reducing LR Iter: 1 	Average training loss: -0.23437 	Val Accuracy: 0.2486 Iter: 101 	Average training loss: -0.24784 	Val Accuracy: 0.2512 Iter: 201 	Average training loss: -0.25124 	Val Accuracy: 0.2527 Iter: 301 	Average training loss: -0.24769 	Val Accuracy: 0.2568 Iter: 401 	Average training loss: -0.25642 	Val Accuracy: 0.2534 Iter: 501 	Average training loss: -0.25162 	Val Accuracy: 0.2565 Iter: 601 	Average training loss: -0.24579 	Val Accuracy: 0.2507 Iter: 701 	Average training loss: -0.25204 	Val Accuracy: 0.2513 
Epoch: 2 Iter: 1 	Average training loss: -0.22338 	Val Accuracy: 0.2515 Iter: 101 	Average training loss: -0.24571 	Val Accuracy: 0.2510 Iter: 201 	Average training loss: -0.24752 	Val Accuracy: 0.2515 Iter: 301 	Average training loss: -0.24821 	Val Accuracy: 0.2532 Iter: 401 	Average training loss: -0.25487 	Val Accuracy: 0.2497 Iter: 501 	Average training loss: -0.25002 	Val Accuracy: 0.2565 Iter: 601 	Average training loss: -0.24876 	Val Accuracy: 0.2525 Iter: 701 	Average training loss: -0.25311 	Val Accuracy: 0.2487 
Epoch: 3 Reducing LR Iter: 1 	Average training loss: -0.22745 	Val Accuracy: 0.2558 Iter: 101 	Average training loss: -0.25016 	Val Accuracy: 0.2529 Iter: 201 	Average training loss: -0.24962 	Val Accuracy: 0.2513 Iter: 301 	Average training loss: -0.24975 	Val Accuracy: 0.2512 Iter: 401 	Average training loss: -0.24638 	Val Accuracy: 0.2523 Iter: 501 	Average training loss: -0.25063 	Val Accuracy: 0.2497 Iter: 601 	Average training loss: -0.24779 	Val Accuracy: 0.2518 Iter: 701 	Average training loss: -0.24812 	Val Accuracy: 0.2470 
Epoch: 4 Iter: 1 	Average training loss: -0.28206 	Val Accuracy: 0.2505 Iter: 101 	Average training loss: -0.25201 	Val Accuracy: 0.2507 Iter: 201 	Average training loss: -0.25283 	Val Accuracy: 0.2492 Iter: 301 	Average training loss: -0.25313 	Val Accuracy: 0.2506 Iter: 401 	Average training loss: -0.25068 	Val Accuracy: 0.2532 Iter: 501 	Average training loss: -0.24702 	Val Accuracy: 0.2474 Iter: 601 	Average training loss: -0.24509 	Val Accuracy: 0.2543 Iter: 701 	Average training loss: -0.24677 	Val Accuracy: 0.2496 
Final Training Accuracy: 0.2493 
Final Validation Accuracy: 0.2482
Final Test Accuracy: 0.2513

**Comment by AnubhavGupta3377** [comment]
So, it's basically Pytorch version that is having the problem.

From this error "**ValueError: optimizing a parameter that doesn't require gradients**", it is clear that your model won't learn anything because it is not optimizing the parameters.

My hunch is that even after making the change, you are basically just avoiding the error message, not actually updating the parameters.

I'll close this issue since it is version specific.

Please let me know if you face any other problem.

**Comment by WindHunter-Yang** [comment]
I  run the code on the torch 0.4.1 very well
