### ISSUE TITLE
Model_Transformer

### ISSUE THREAD

**Issue by iranusSu** [AnubhavGupta3377/Text-Classification-Models#7]
Hi, would you please share your point in "Only encoder part of Transformer model is used for classification",.
I apply this model in my dataset, the accuracy only 60% .I am thinking whether the number of layer is a cause?

**Comment by AnubhavGupta3377** [comment]
Hi, Decoder part is useful when you are trying to generate some sequential output, such as in machine translation, question answering, etc. For classification, you just need to use encoder to create the text embeddings, and then use fully connected layer(s) to classify the text.

You can try experimenting with the number of layers to improve the performance. Or the specific task may be just too difficult for the model.

Ask yourself this question: **What is the state of the art classification accuracy on this dataset?**

If it's close to 60%, then Transformer won't give you much better results just be tuning the parameters.

**Comment by iranusSu** [comment]
Thanks a lot for your reply!  
And my partner use Lstm can get 98% accuracy.So i am so confused, because  i believe that the attention mechanism in Transformer can also capture the feature in long text(sequence).
